package git

import (
	"github.com/gitamix/types/commit"
)

// Option defines a functional option to configure
// the Params of the git rev-list command
// executed by the Commits method of Client.
type Option func(*Params)

// Params holds the parameters of the git rev-list command
// executed by the Commits method of Client.
type Params struct {
	// firstParent tells the git rev-list command
	// to follow only the first parent of each commit.
	firstParent bool
	// noMerges tells the git rev-list command
	// to exclude merge commits from the result.
	noMerges bool
}

// NewParams creates a new Params instance with the provided options.
//
// Parameters:
//   - opts: The functional options to configure the Params.
func NewParams(opts ...Option) Params {
	p := Params{}
	for _, opt := range opts {
		opt(&p)
	}
	return p
}

// WithFirstParent returns an Option that tells
// the git rev-list command to follow only the first parent of each commit.
//
// It limits the listed commits to the first-parent ancestry,
// excluding the commits brought into the current branch by merge commits.
func WithFirstParent() Option {
	return func(p *Params) {
		p.firstParent = true
	}
}

// WithNoMerges returns an Option that tells
// the git rev-list command to exclude merge commits from the result.
//
// It is useful to skip merge commits
// whose messages are generated by Git itself.
func WithNoMerges() Option {
	return func(p *Params) {
		p.noMerges = true
	}
}

// Flags returns the flags of the git rev-list command defined by the Params.
func (p Params) Flags() []string {
	flags := []string{
		"rev-list",
		"--abbrev-commit",
	}
	if p.firstParent {
		flags = append(flags, "--first-parent")
	}
	if p.noMerges {
		flags = append(flags, "--no-merges")
	}
	return flags
}

// Args returns the arguments of the git rev-list command
// defined by the Params for the specified exclusive start hash.
//
// Parameters:
//   - hash: The commit hash to list the commits after, exclusive.
func (p Params) Args(hash commit.Hash) []string {
	return append(
		p.Flags(),
		hash.String()+"..HEAD",
	)
}
